import type {
  Concept,
  Evidence,
  Person,
  Skill,
  WorkObject,
} from "./types";

export const person: Person = {
  name: "Sahil Shitole",
  title: "Software Engineer",
  positioning: "Backend Systems × Applied AI",
  location: "Pune, India",
  experience: "Approximately 1.5 years of professional experience",
  email: "sahilmshitole1483@gmail.com",
  phone: "+91-7620919774",
  linkedin: "https://www.linkedin.com/in/sahil-shitole/",
  github: "https://github.com/Sms1818",
  resumePath: "/resume/Sahil_Shitole_Resume.pdf",
  about: `I’m a software engineer who enjoys building systems that solve real operational problems. Over the past ~1.5 years, I’ve worked across backend engineering, automation, and applied AI — building Spring Boot microservices, secure APIs, integrations, internal tools, and AI-assisted workflows used in day-to-day operations.

I’m most comfortable with Java, Spring Boot, Python, FastAPI, and SQL, but I’m less attached to a particular stack than I am to understanding the problem and building the right system around it. That has taken me from designing APIs and event-driven workflows to working with LLMs, RAG, external integrations, and deployment.

Outside of work, I like building things end to end. I built PRSense, an event-driven AI code review system; experimented with product-focused AI MVPs like VeriSpec and FlowDoctor; and contributed to the open-source Caspian SDK.

The kind of work I’m looking for sits at the intersection of backend systems, applied AI, and product engineering — especially on a team where I can own problems, ship real software, and keep getting better at the engineering underneath it.`,
  education: {
    degree: "B.Tech in Computer Science and Engineering",
    school: "Vishwakarma Institute of Technology, Pune",
    years: "2021–2025",
    cgpa: "8.71",
  },
  targetRoles: [
    "Software Engineer",
    "Software Developer",
    "Backend Engineer",
    "Backend Developer",
    "AI Engineer",
    "AI Developer",
    "Applied AI Engineer",
    "backend-heavy Full-Stack Engineer",
    "Forward Deployed Engineer",
    "Solutions Engineering roles involving APIs, integrations, automation, or AI systems",
  ],
  strengths: [
    "Building systems end-to-end: problem/requirements → backend → database → APIs/integrations → deployment → debugging.",
    "Backend and integration engineering across Java, Spring Boot, Python, SQL, REST APIs, and external systems.",
    "Applied AI combined with deterministic software: AI handles ambiguity; software controls state, guarantees, and actions.",
    "Automation with measurable outcomes: AR workflow for 50+ accounts, four legacy applications consolidated, ~4 hours/week reporting savings.",
    "Working across system boundaries and external APIs.",
    "Engineering self-awareness — including honest discussion of PRSense limitations.",
    "Working in another team’s codebase, evidenced by merged Caspian SDK contributions.",
  ],
  limitations: [
    "Frontend evidence exists through end-to-end MVPs, but backend evidence is stronger. Frontend is not the strongest specialization.",
    "No evidence currently establishes that Sahil has operated internet-scale distributed systems in production.",
    "There is DigitalOcean, Docker, GitHub Actions, and project-level Kubernetes evidence. The portfolio does not establish deep AWS/GCP production expertise.",
    "Approximately 1.5 years of professional experience — not senior/staff/principal level.",
    "Some technologies have hands-on project evidence rather than professional-production evidence. Kafka is an important example.",
  ],
  gaps: [
    "The portfolio does not currently provide evidence of Terraform experience.",
    "The portfolio does not currently provide evidence of production AWS expertise.",
    "The portfolio does not currently provide evidence of employment at Google or other unlisted companies.",
  ],
};

export const work: WorkObject[] = [
  {
    id: "neopart",
    slug: "neopart",
    name: "Neopart Transit LLC",
    classification: "PROFESSIONAL",
    eyebrow: "Via Blue Ocean Global · Jan 2025 – May 2026",
    summary:
      "Software Engineer – Backend & Automation. Production backend services, APIs, integrations, automation, and applied AI used in day-to-day operations.",
    story:
      "At Neopart Transit, Sahil built backend services, secure APIs, integrations, internal tools, and AI-assisted operational workflows. The work is professional software-engineering evidence: production systems, measurable operational impact, and responsibility across APIs, data, deployment, and debugging.",
    technologies: [
      "Java",
      "Spring Boot",
      "Spring MVC",
      "Spring Security",
      "Spring Data JPA",
      "Hibernate",
      "Python",
      "FastAPI",
      "Flask",
      "SQL Server",
      "MySQL",
      "REST APIs",
      "JWT",
      "RBAC",
      "GitHub Actions",
      "DigitalOcean",
      "Docker",
    ],
    links: [],
    inspectorTabs: [
      "overview",
      "impact",
      "ar-escalation",
      "integrations",
      "apis",
      "deployment",
      "technology",
      "evidence",
    ],
    sections: {
      overview:
        "Professional backend and automation work at Neopart Transit LLC (via Blue Ocean Global), January 2025 – May 2026. Portfolio title: Software Engineer – Backend & Automation.",
      impact:
        "Consolidated 4 legacy accounting applications into Spring Boot microservices. Built an AR escalation system supporting 50+ customer accounts. Automated recurring reporting, saving approximately 4 hours/week. Also built B2B portal functionality around scheduling, parts, pricing, and access control.",
      "ar-escalation":
        "Built a customer-level accounts-receivable escalation system supporting 50+ customer accounts. It covers overdue invoices, interactions, payment commitments, escalation history, and business rules. LLMs assist with interpreting unstructured customer interactions. Deterministic software controls state, guarantees, and actions. The LLM does not autonomously control financial workflows.",
      integrations:
        "Built Python/FastAPI integrations across Quickbase, OptimoRoute, QuickBooks, and Office 365 via REST APIs, automating AR follow-ups, field-visit scheduling, and operational workflows.",
      apis:
        "Built secure REST APIs using Spring Boot, Spring Data JPA, Hibernate, Spring Security, JWT, and role-based access control. Developed a B2B customer portal backend supporting scheduling, parts ordering, and tiered pricing.",
      deployment:
        "Worked with GitHub Actions CI/CD pipelines on DigitalOcean, including production deployments, infrastructure operations, and backend debugging.",
      technology:
        "Java, Spring Boot, Spring MVC, Spring Security, Spring Data JPA, Hibernate, Python, FastAPI, Flask, SQL Server, MySQL, REST APIs, JWT, RBAC, GitHub Actions, DigitalOcean, Docker, and external integrations.",
      evidence:
        "This is professional production evidence. There are no public source repositories for this proprietary work.",
    },
    achievements: [
      {
        id: "neopart-ar",
        title: "AR escalation system",
        body: "Built a customer-level accounts-receivable escalation system supporting 50+ customer accounts, using LLMs to interpret unstructured interactions while deterministic rules managed payment commitments, follow-up timing, and escalation workflows.",
        metrics: ["50+ customer accounts"],
        evidenceIds: ["ev-neopart-ar"],
      },
      {
        id: "neopart-legacy",
        title: "Legacy consolidation",
        body: "Consolidated 4 legacy accounting applications into Spring Boot microservices with RESTful APIs and MySQL.",
        metrics: ["4 legacy applications"],
        evidenceIds: ["ev-neopart-legacy"],
      },
      {
        id: "neopart-reporting",
        title: "Reporting automation",
        body: "Developed Python, Java, and SQL Server automations that eliminated approximately 4 hours of recurring manual reporting work per week.",
        metrics: ["~4 hours/week"],
        evidenceIds: ["ev-neopart-reporting"],
      },
    ],
    evidenceIds: [
      "ev-neopart-ar",
      "ev-neopart-legacy",
      "ev-neopart-apis",
      "ev-neopart-integrations",
      "ev-neopart-reporting",
      "ev-neopart-cicd",
      "ev-neopart-portal",
    ],
  },
  {
    id: "prsense",
    slug: "prsense",
    name: "PRSense",
    classification: "ENGINEERING PROJECT",
    eyebrow: "Event-driven AI code-review platform",
    summary:
      "An AI-assisted event-driven code review system. The interesting part is not calling Gemini — it is coordinating multiple independently failing systems around it.",
    story:
      "A Bitbucket webhook enters through a Spring service, is persisted and published through Kafka, consumed asynchronously, translated into a merge-base Git diff, sent to Gemini, validated, and finally written back through the Bitbucket API. Git, Kafka, Gemini, and Bitbucket can each fail independently.",
    technologies: [
      "Java 21",
      "Spring Boot 3.5",
      "Spring Cloud Gateway",
      "Kafka",
      "PostgreSQL",
      "JGit",
      "Gemini 2.5 Flash",
      "Bitbucket APIs",
      "Bitbucket webhooks",
      "WebClient",
      "Docker",
      "Kubernetes",
      "Maven",
    ],
    links: [
      {
        label: "GitHub",
        href: "https://github.com/Sms1818/PRSense",
        kind: "github",
      },
    ],
    inspectorTabs: [
      "overview",
      "architecture",
      "event-flow",
      "how-it-works",
      "why-async",
      "git-diff",
      "ai-boundary",
      "failure-handling",
      "decisions",
      "limitations",
      "improve",
      "scale",
      "technology",
      "evidence",
    ],
    architecture: {
      nodes: [
        {
          id: "webhook",
          label: "Bitbucket webhook",
          detail: "Pull-request events enter the system.",
          kind: "ingress",
        },
        {
          id: "gateway",
          label: "Gateway / Spring service",
          detail: "Accepts the event in a Spring service path.",
          kind: "service",
        },
        {
          id: "persist",
          label: "Persist event",
          detail: "The event is stored in PostgreSQL.",
          kind: "data",
        },
        {
          id: "kafka",
          label: "Kafka",
          detail: "Decouples ingestion from the longer-running review pipeline.",
          kind: "queue",
        },
        {
          id: "consumer",
          label: "Async consumer",
          detail: "Picks up the review job independently of webhook acknowledgement.",
          kind: "worker",
        },
        {
          id: "clone",
          label: "Repository clone",
          detail: "JGit handles SSH clone and fetch.",
          kind: "worker",
        },
        {
          id: "diff",
          label: "Merge-base diff",
          detail: "Native Git CLI computes merge-base then diff.",
          kind: "worker",
        },
        {
          id: "gemini",
          label: "Gemini 2.5 Flash",
          detail: "Receives the diff and produces review content. Does not control workflow.",
          kind: "ai",
        },
        {
          id: "validate",
          label: "Response validation",
          detail: "Malformed or empty Gemini responses are treated as failures.",
          kind: "service",
        },
        {
          id: "comment",
          label: "Bitbucket PR comment",
          detail: "Validated review content is posted back through the Bitbucket API.",
          kind: "external",
        },
      ],
      flow: [
        "Bitbucket webhook",
        "gateway / Spring service",
        "event persisted",
        "Kafka",
        "async consumer",
        "repository clone",
        "merge-base diff",
        "Gemini review",
        "response validation",
        "Bitbucket PR comment",
      ],
      canonicalStory:
        "The interesting part of PRSense isn't calling Gemini. It's coordinating multiple independently failing systems around it. A Bitbucket webhook enters through a Spring service, is persisted and published through Kafka, consumed asynchronously, translated into a merge-base Git diff, sent to Gemini, validated, and finally written back through the Bitbucket API. That architecture creates real failure boundaries: Git, Kafka, Gemini and Bitbucket can each fail independently. The project already isolates the asynchronous workflow and handles external API failures explicitly, while the current implementation also exposes several production-hardening opportunities—particularly idempotency, Git-stage error propagation, dead-letter recovery and workspace lifecycle management.",
    },
    sections: {
      overview:
        "PRSense is an AI-assisted event-driven code review system. It is an engineering project, not a proven high-scale production platform.",
      architecture:
        "Bitbucket webhook → gateway / Spring service → event persisted → Kafka → async consumer → repository clone → merge-base diff → Gemini review → response validation → Bitbucket PR comment.",
      "event-flow":
        "Ingestion is separated from processing. The review service accepts and persists Bitbucket events, then publishes them. A consumer performs clone, diff, inference, validation, and comment posting asynchronously.",
      "how-it-works":
        "Webhook receipt is the start of a deterministic workflow: persist → publish → clone → diff → Gemini → validate → Bitbucket. Gemini produces review content; it does not decide repository routing, event state, system actions, or workflow ordering.",
      "why-async":
        "Kafka decouples webhook ingestion from the longer-running code-review pipeline. Bitbucket events are accepted and persisted by the review service, while repository cloning, diff generation, AI inference and PR feedback are handled asynchronously by a separate consumer. This is an architectural explanation, not an incident or scalability story.",
      "git-diff":
        "JGit is used for SSH clone and fetch because it was a reasonable Java-native implementation choice for cloning/fetching. Native Git CLI is used for branch inspection, merge-base, and diff. The system determines git merge-base HEAD origin/<targetBranch>, then git diff <mergeBaseCommit> HEAD, focusing the review on changes between the common ancestor and the feature branch HEAD.",
      "ai-boundary":
        "Gemini receives the code diff and produces review content covering bugs, performance, security, code quality, and best practices, asking for severity, explanation, and suggested fix. Gemini does not decide repository routing, event state, system actions, or workflow ordering. Do not treat PRSense as a highly autonomous agent.",
      "failure-handling":
        "Clone exceptions are currently caught and logged without rethrowing, so the pipeline may continue. Diff errors can return an empty string, which can look like “No code changes detected.” Git-stage operational failures are not distinguished strongly enough from a legitimate empty diff. Gemini failures do not silently create fake successful reviews; they propagate into the consumer, which catches, logs, and rethrows. Malformed or empty Gemini responses are treated as failures. Bitbucket comment failures also propagate; the workflow is not implied to have succeeded if the external comment failed.",
      decisions:
        "Kafka was chosen to decouple ingestion from a longer-running pipeline. JGit was a reasonable Java-native choice for clone/fetch. Native Git CLI is used where merge-base and diff operations are needed. AI is confined to review generation inside a deterministic workflow.",
      limitations:
        "There is currently no strong explicit idempotency mechanism: a duplicate webhook may create another database event, Kafka event, AI review, and potentially another Bitbucket comment. kafkaTemplate.send(...) does not fully establish a reliable DB-persist → Kafka-ack transactional boundary. There is no strong application-level dead-letter, retry-topic, replay, or recovery state machine. Repository location is based on repositories/<sourceBranch>; existing directories may be removed before cloning, with no strong finally-based post-job cleanup. Configurable timeout/backoff infrastructure exists, while HTTP error wrapping is an area that should be refined so status-aware retry classification is preserved end to end. Webhook signature verification is a potential hardening area and is not claimed as an implemented property.",
      improve:
        "Propagate explicit clone/diff failures; bounded retries; dead-letter/recovery handling; distinguish operational failure from valid empty result; deterministic idempotency key involving workspace, repository, pull-request ID, and source commit SHA; reliable publication / transactional outbox; unique temporary workspace per review with cleanup in finally; isolated concurrent workspaces; refine HTTP error wrapping so status-aware retries are preserved end to end.",
      scale:
        "PRSense has not been shown to process internet-scale production traffic. A clear scaling path — not proven scale — would include Kafka partitions, multiple stateless review workers, unique temporary workspaces, bounded concurrency, diff/token management, Gemini and Bitbucket rate limiting, retry topics, DLQ, an idempotency store, metrics/tracing, and reliable event publication. Current potential bottlenecks include a single AI service replica in current manifests, local repository disk, branch-based workspace paths, limited concurrency isolation, external API rate limits, missing idempotency, missing explicit DLQ/replay, workspace cleanup, and potentially large diffs sent directly to Gemini.",
      technology:
        "Java 21, Spring Boot 3.5, Spring Cloud Gateway, Kafka, PostgreSQL, JGit, Gemini 2.5 Flash, Bitbucket APIs and webhooks, WebClient, Docker, Kubernetes, Maven.",
      evidence:
        "Hands-on engineering-project evidence. Kafka evidence is project-level, not documented professional-production Kafka experience. Source: https://github.com/Sms1818/PRSense",
    },
    decisions: [
      {
        id: "prsense-kafka",
        title: "Why Kafka",
        body: "Kafka decouples webhook ingestion from the longer-running code-review pipeline. Bitbucket events are accepted and persisted by the review service, while repository cloning, diff generation, AI inference and PR feedback are handled asynchronously by a separate consumer.",
        evidenceIds: ["ev-prsense-kafka"],
      },
      {
        id: "prsense-jgit",
        title: "Why JGit for clone/fetch",
        body: "JGit was a reasonable Java-native implementation choice for cloning and fetching. Native Git CLI is used for branch inspection, merge-base, and diff.",
        evidenceIds: ["ev-prsense-git"],
      },
      {
        id: "prsense-ai-boundary",
        title: "Keep Gemini inside a deterministic workflow",
        body: "Gemini produces review content. The workflow remains webhook → persist → publish → clone → diff → Gemini → validate → Bitbucket. Gemini does not control routing, state, or actions.",
        evidenceIds: ["ev-prsense-ai-boundary"],
      },
    ],
    limitations: [
      {
        id: "clone-failure",
        title: "Clone failure can be swallowed",
        body: "Current implementation catches clone exceptions and logs them without rethrowing. The pipeline may continue. A later diff failure can return an empty string, which can look like “No code changes detected.” Git-stage operational failures are not currently distinguished strongly enough from a legitimate empty diff.",
        improvement:
          "Propagate explicit clone/diff failures, add bounded retries where appropriate, introduce dead-letter/recovery handling, and distinguish operational failure from a valid empty result.",
        href: "/explore/projects/prsense/limitations/clone-failure",
      },
      {
        id: "diff-failure",
        title: "Empty diff vs operational failure",
        body: "Diff errors are caught and can return an empty string. The caller cannot reliably distinguish a valid empty diff from an operational failure.",
        improvement:
          "Return typed errors from the Git stage so empty results and failures are distinct.",
        href: "/explore/projects/prsense/limitations/diff-failure",
      },
      {
        id: "idempotency",
        title: "Duplicate webhooks",
        body: "There is currently no strong explicit idempotency mechanism. A duplicate webhook may create another database event, another Kafka event, another AI review, and potentially another Bitbucket comment.",
        improvement:
          "Use a deterministic idempotency key involving workspace, repository, pull-request ID, and source commit SHA, and check it before expensive processing.",
        href: "/explore/projects/prsense/limitations/idempotency",
      },
      {
        id: "kafka-publication",
        title: "Persist → publish boundary",
        body: "The producer sends using kafkaTemplate.send(...). The current implementation does not fully establish a reliable DB-persist → Kafka-ack transactional boundary.",
        improvement: "Reliable publication and a transactional outbox.",
        href: "/explore/projects/prsense/limitations/kafka-publication",
      },
      {
        id: "consumer-recovery",
        title: "Consumer recovery",
        body: "Consumer exceptions can propagate. There is no strong application-level dead-letter strategy, retry-topic strategy, explicit replay workflow, or recovery state machine.",
        improvement:
          "Add retry topics, DLQ, and an explicit replay/recovery path.",
        href: "/explore/projects/prsense/limitations/consumer-recovery",
      },
      {
        id: "workspace-lifecycle",
        title: "Repository lifecycle",
        body: "Repository location is based on a path such as repositories/<sourceBranch>. Before cloning, an existing directory may be removed. There is no strong finally-based post-job cleanup.",
        improvement:
          "Unique temporary workspace per review, cleanup in finally, and isolated concurrent workspaces.",
        href: "/explore/projects/prsense/limitations/workspace-lifecycle",
      },
      {
        id: "retry-wrapping",
        title: "Retry classification",
        body: "Configurable timeout and backoff infrastructure exists (Gemini: max retries 3, initial delay 2s, max delay 15s, timeout 60s; Bitbucket: max retries 3, initial delay 1s, max delay 10s, timeout 30s). The retry predicate understands HTTP 5xx, 429, timeout, and I/O failures. Current clients wrap some HTTP failures in generic runtime exceptions before retry classification, so status-aware retry behavior is not claimed to work perfectly end to end.",
        improvement:
          "Preserve status-aware retry classification through the HTTP client boundary.",
        href: "/explore/projects/prsense/limitations/retry-wrapping",
      },
      {
        id: "webhook-security",
        title: "Webhook security",
        body: "Webhook signature verification is not claimed as an implemented property of the current PRSense implementation. Treat it as a potential hardening area.",
        improvement: "Add webhook signature verification where appropriate.",
        href: "/explore/projects/prsense/limitations/webhook-security",
      },
    ],
    evidenceIds: [
      "ev-prsense-overview",
      "ev-prsense-kafka",
      "ev-prsense-git",
      "ev-prsense-ai-boundary",
      "ev-prsense-failures",
      "ev-prsense-k8s",
    ],
  },
  {
    id: "supportsync",
    slug: "supportsync",
    name: "SupportSync",
    classification: "ENGINEERING PROJECT",
    eyebrow: "Intelligent support platform",
    summary:
      "FastAPI support platform with semantic retrieval over historically solved tickets, a document chatbot, and integrations with Jira, ClickUp, and Salesforce.",
    story:
      "SupportSync centralizes ticket data across Jira, ClickUp, and Salesforce, then uses LangChain and Pinecone for semantic retrieval over historically solved support tickets. It also includes document chatbot functionality. This is engineering-project evidence. Do not invent production deployment or user metrics.",
    technologies: [
      "Python",
      "FastAPI",
      "Jira",
      "ClickUp",
      "Salesforce",
      "LangChain",
      "Pinecone",
      "RAG",
      "Groq / Llama",
      "Docker",
    ],
    links: [
      {
        label: "GitHub",
        href: "https://github.com/Sms1818/Support_Sync_Project",
        kind: "github",
      },
    ],
    inspectorTabs: [
      "overview",
      "workflow",
      "rag",
      "integrations",
      "technology",
      "evidence",
    ],
    sections: {
      overview:
        "SupportSync is an engineering project: a FastAPI-based support platform that centralizes ticket data and generates context-aware resolution suggestions. No production deployment or user metrics are claimed.",
      workflow:
        "Ticket data from Jira, ClickUp, and Salesforce is centralized. Semantic retrieval surfaces historically solved tickets. A document-enabled chatbot can answer from documents. The application is containerized with Docker.",
      rag: "Semantic retrieval with LangChain and Pinecone surfaces relevant historical tickets and generates context-aware support recommendations. Groq / Llama is part of the relevant technology set.",
      integrations:
        "Cross-system integrations include Jira, ClickUp, and Salesforce.",
      technology:
        "Python, FastAPI, Jira, ClickUp, Salesforce, LangChain, Pinecone, RAG, Groq / Llama, Docker.",
      evidence:
        "Engineering-project evidence for RAG, FastAPI, and support-system integrations. Source: https://github.com/Sms1818/Support_Sync_Project",
    },
    evidenceIds: ["ev-supportsync-rag", "ev-supportsync-integrations"],
  },
  {
    id: "verispec",
    slug: "verispec",
    name: "VeriSpec",
    classification: "MVP",
    eyebrow: "End-to-end AI product MVP",
    summary:
      "A deployed AI product MVP demonstrating product judgment, frontend/full-stack execution, and idea → shipped workflow.",
    story:
      "VeriSpec is an MVP. It demonstrates product judgment, frontend/full-stack execution, an AI workflow, validation, and deployment. It is not a mature production platform.",
    technologies: ["AI workflow", "frontend/full-stack", "deployment"],
    links: [
      { label: "GitHub", href: "https://github.com/Sms1818/VeriSpec", kind: "github" },
      { label: "Live", href: "https://veri-spec-rho.vercel.app/", kind: "live" },
      {
        label: "Demo",
        href: "https://www.loom.com/share/6880f60a811647f983c85aa3191c6550",
        kind: "demo",
      },
    ],
    inspectorTabs: ["overview", "product", "evidence"],
    sections: {
      overview:
        "VeriSpec is an end-to-end AI product MVP. Always classify it as an MVP. It is not a mature production platform.",
      product:
        "It demonstrates product judgment, frontend/full-stack execution, idea → deployed MVP, AI workflow, validation, and deployment.",
      evidence:
        "MVP evidence for product/MVP execution and some frontend/end-to-end capability. Live: https://veri-spec-rho.vercel.app/",
    },
    evidenceIds: ["ev-verispec"],
  },
  {
    id: "flowdoctor",
    slug: "flowdoctor",
    name: "FlowDoctor",
    classification: "MVP",
    eyebrow: "AI-assisted workflow review MVP",
    summary:
      "Explores AI-assisted workflow review across reliability, security, observability, cost, and architecture.",
    story:
      "FlowDoctor is an MVP exploring AI-assisted workflow review. It is not a production platform.",
    technologies: [
      "AI-assisted review",
      "reliability",
      "security",
      "observability",
      "cost",
      "architecture",
    ],
    links: [
      { label: "GitHub", href: "https://github.com/Sms1818/FlowDoctor", kind: "github" },
      { label: "Live", href: "https://flow-doctor-coral.vercel.app/", kind: "live" },
      {
        label: "Demo",
        href: "https://drive.google.com/file/d/16yispMfn6X-60Uviq6Uz9Q0linlyjmfm/view?usp=drive_link",
        kind: "demo",
      },
    ],
    inspectorTabs: ["overview", "product", "evidence"],
    sections: {
      overview:
        "FlowDoctor is an MVP. It explores AI-assisted workflow review across reliability, security, observability, cost, and architecture.",
      product:
        "The value is product-focused: reviewing workflows with AI assistance. Do not present it as a mature production platform.",
      evidence:
        "MVP evidence for product execution and workflow-review thinking. Live: https://flow-doctor-coral.vercel.app/",
    },
    evidenceIds: ["ev-flowdoctor"],
  },
  {
    id: "lenny",
    slug: "lenny",
    name: "Lenny Growth Assistant",
    classification: "MVP",
    eyebrow: "RAG chat MVP",
    summary:
      "MVP exploring FastAPI, PostgreSQL, pgvector, RAG, persistent chat, local/cloud LLM approaches, evaluations, and frontend.",
    story:
      "Lenny is an MVP and is lower priority than PRSense and the strongest professional evidence. It contributes RAG and product/MVP evidence.",
    technologies: [
      "FastAPI",
      "PostgreSQL",
      "pgvector",
      "RAG",
      "persistent chat",
      "local/cloud LLM",
      "evaluations",
      "frontend",
    ],
    links: [
      {
        label: "GitHub",
        href: "https://github.com/Sms1818/lenny-growth-assistant",
        kind: "github",
      },
      {
        label: "Demo",
        href: "https://www.loom.com/share/75ccefd82a4c4c60bf3cda657c8b2ec3",
        kind: "demo",
      },
    ],
    inspectorTabs: ["overview", "product", "evidence"],
    sections: {
      overview:
        "Lenny Growth Assistant is an MVP. Relevant concepts include FastAPI, PostgreSQL, pgvector, RAG, persistent chat, local/cloud LLM approaches, evaluations, and frontend.",
      product:
        "Lower priority than PRSense and Neopart. Useful as RAG and product/MVP evidence. Not a production platform.",
      evidence:
        "MVP evidence for RAG and end-to-end product execution. Demo: Loom recording linked from the project.",
    },
    evidenceIds: ["ev-lenny"],
  },
  {
    id: "caspian",
    slug: "caspian",
    name: "Caspian SDK",
    classification: "OPEN SOURCE",
    eyebrow: "Bluesky / AT Protocol · 2 merged PRs",
    summary:
      "Extended an external messaging SDK with first-class Bluesky support, then iterated on session reliability and per-account concurrency after review.",
    story:
      "Two merged PRs in an external codebase. This is open-source validation: API integration, authentication/session lifecycle, polling, webhooks, testing, review iteration, adapting to upstream architecture changes, and concurrency reasoning via per-account session locking.",
    technologies: [
      "AT Protocol",
      "Bluesky",
      "webhooks",
      "polling",
      "authentication",
      "concurrency",
      "testing",
    ],
    links: [
      {
        label: "PR #94",
        href: "https://github.com/TryCaspian/caspian-sdk/pull/94",
        kind: "pr",
      },
      {
        label: "PR #140",
        href: "https://github.com/TryCaspian/caspian-sdk/pull/140",
        kind: "pr",
      },
    ],
    inspectorTabs: ["overview", "pr-94", "pr-140", "concurrency", "evidence"],
    sections: {
      overview:
        "Open Source Contribution · 2 merged PRs. Extended an external messaging SDK with first-class Bluesky support, including outbound posts and threaded replies, inbound notification polling, webhook verification, message normalization, offline fakes and tests. Iterated on the integration after review to add cached and refreshable authentication sessions, retry-on-401 behavior and per-account concurrency control. Also rebased and ported the implementation when the upstream repository changed architecture during development.",
      "pr-94":
        "PR #94 added Bluesky / AT Protocol support: session provisioning, posts, threaded replies, inbound notification polling, webhook verification, normalization into the Caspian messaging model, a fake provider, registry/config integration, and offline tests. During development the upstream adapter architecture changed; the implementation was rebased/ported into the newer provider architecture and updated through review cycles. A polling cursor edge case was identified involving notifications sharing timestamps. A broad cursor-semantics redesign was intentionally kept outside the PR’s scope because it required broader persisted cursor semantics and additional boundary state.",
      "pr-140":
        "PR #140 improved session and processing reliability: cached authenticated sessions, session reuse, automatic token refresh following 401, fresh-session fallback, centralized authenticated request handling, and immediate processing acknowledgement for inbound messages. A process-wide session lock was identified as unnecessarily serializing authentication across different accounts. It was changed to per-account session locking so unrelated accounts can proceed concurrently while refresh operations for the same account stay protected. This is valid hands-on concurrency evidence — not a claim of distributed-systems concurrency expertise.",
      concurrency:
        "Per-account session locking allows unrelated accounts to proceed concurrently while protecting refresh operations for the same account. Focused external evidence from Caspian PR #140.",
      evidence:
        "Two merged PRs: https://github.com/TryCaspian/caspian-sdk/pull/94 and https://github.com/TryCaspian/caspian-sdk/pull/140.",
    },
    evidenceIds: ["ev-caspian-94", "ev-caspian-140"],
  },
];

export const evidence: Evidence[] = [
  {
    id: "ev-neopart-ar",
    claim: "AR escalation system supporting 50+ customer accounts",
    summary:
      "Professional evidence: customer-level AR escalation with LLM-assisted interpretation and deterministic escalation logic.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/ar-escalation",
    tags: ["applied ai", "automation", "backend", "business rules", "llm"],
  },
  {
    id: "ev-neopart-legacy",
    claim: "Consolidated 4 legacy accounting applications into Spring Boot microservices",
    summary: "Professional Java/Spring Boot microservices work on accounting workflows.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/impact",
    tags: ["java", "spring boot", "microservices", "mysql"],
  },
  {
    id: "ev-neopart-apis",
    claim: "Secure REST APIs with Spring Security, JWT, JPA/Hibernate, and RBAC",
    summary: "Professional API security and backend design evidence.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/apis",
    tags: ["rest", "spring security", "jwt", "rbac", "hibernate", "jpa"],
  },
  {
    id: "ev-neopart-integrations",
    claim: "Integrations with Quickbase, OptimoRoute, QuickBooks, and Office 365",
    summary: "Professional FastAPI/Python REST integrations for operational workflows.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/integrations",
    tags: ["python", "fastapi", "integrations", "quickbase", "quickbooks", "optimoroute", "office 365"],
  },
  {
    id: "ev-neopart-reporting",
    claim: "Automated recurring reporting, saving approximately 4 hours/week",
    summary: "Professional Python, Java, and SQL Server automation with a measured outcome.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/impact",
    tags: ["sql", "automation", "python", "java", "sql server"],
  },
  {
    id: "ev-neopart-cicd",
    claim: "GitHub Actions CI/CD on DigitalOcean with production debugging",
    summary: "Professional deployment and operations evidence. Not AWS production evidence.",
    sourceType: "PROFESSIONAL",
    strength: "GOOD",
    objectId: "neopart",
    href: "/explore/experience/neopart/deployment",
    tags: ["github actions", "digitalocean", "docker", "ci/cd", "production debugging"],
    caveat: "This is DigitalOcean/GitHub Actions evidence, not production AWS expertise.",
  },
  {
    id: "ev-neopart-portal",
    claim: "B2B portal backend for scheduling, parts, pricing, and access control",
    summary: "Professional Spring Security/JWT portal backend evidence.",
    sourceType: "PROFESSIONAL",
    strength: "STRONG",
    objectId: "neopart",
    href: "/explore/experience/neopart/apis",
    tags: ["spring security", "jwt", "rbac", "backend"],
  },
  {
    id: "ev-prsense-overview",
    claim: "Event-driven AI-assisted code review platform",
    summary: "Engineering-project evidence for backend systems, async processing, and AI integration.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "STRONG",
    objectId: "prsense",
    href: "/explore/projects/prsense",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["java", "spring boot", "event-driven", "backend"],
  },
  {
    id: "ev-prsense-kafka",
    claim: "Kafka decouples webhook ingestion from the review pipeline",
    summary:
      "Hands-on project evidence for Kafka and event-driven architecture. Not documented professional-production Kafka experience.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "GOOD",
    objectId: "prsense",
    href: "/explore/projects/prsense/why-async",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["kafka", "async", "event-driven", "reliability"],
    caveat:
      "Kafka evidence is hands-on project evidence rather than documented professional-production experience.",
  },
  {
    id: "ev-prsense-git",
    claim: "JGit clone/fetch plus native Git merge-base diff",
    summary: "Concrete Git pipeline: merge-base then diff against feature HEAD.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "GOOD",
    objectId: "prsense",
    href: "/explore/projects/prsense/git-diff",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["jgit", "git", "diff", "bitbucket"],
  },
  {
    id: "ev-prsense-ai-boundary",
    claim: "Gemini generates reviews inside a deterministic workflow",
    summary: "Applied AI with a clear boundary: Gemini does not control routing, state, or actions.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "STRONG",
    objectId: "prsense",
    href: "/explore/projects/prsense/ai-boundary",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["gemini", "llm", "applied ai", "ai boundary"],
  },
  {
    id: "ev-prsense-failures",
    claim: "Independent failure boundaries across Git, Kafka, Gemini, and Bitbucket",
    summary:
      "Honest engineering evidence: some failures propagate; Git-stage failures are currently under-distinguished; idempotency and DLQ remain gaps.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "GOOD",
    objectId: "prsense",
    href: "/explore/projects/prsense/failure-handling",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["reliability", "failure handling", "idempotency", "retries"],
  },
  {
    id: "ev-prsense-k8s",
    claim: "Docker and Kubernetes packaging for PRSense services",
    summary: "Project evidence for Docker/Kubernetes. Not a claim of large-scale cluster operations.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "LIMITED",
    objectId: "prsense",
    href: "/explore/projects/prsense/technology",
    github: "https://github.com/Sms1818/PRSense",
    tags: ["docker", "kubernetes"],
    caveat: "Kubernetes evidence is project-level from PRSense manifests.",
  },
  {
    id: "ev-supportsync-rag",
    claim: "RAG over historically solved support tickets",
    summary: "Engineering-project evidence for LangChain, Pinecone, and semantic retrieval.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "GOOD",
    objectId: "supportsync",
    href: "/explore/projects/supportsync/rag",
    github: "https://github.com/Sms1818/Support_Sync_Project",
    tags: ["rag", "langchain", "pinecone", "python", "fastapi"],
  },
  {
    id: "ev-supportsync-integrations",
    claim: "Jira, ClickUp, and Salesforce integrations",
    summary: "Engineering-project evidence for cross-system support integrations.",
    sourceType: "ENGINEERING_PROJECT",
    strength: "GOOD",
    objectId: "supportsync",
    href: "/explore/projects/supportsync/integrations",
    github: "https://github.com/Sms1818/Support_Sync_Project",
    tags: ["jira", "clickup", "salesforce", "integrations"],
  },
  {
    id: "ev-verispec",
    claim: "Deployed AI product MVP",
    summary: "MVP evidence for product judgment and end-to-end execution. Not a production platform.",
    sourceType: "MVP",
    strength: "GOOD",
    objectId: "verispec",
    href: "/explore/mvps/verispec",
    github: "https://github.com/Sms1818/VeriSpec",
    tags: ["mvp", "product", "frontend", "deployment"],
  },
  {
    id: "ev-flowdoctor",
    claim: "AI-assisted workflow review MVP",
    summary: "MVP exploring reliability, security, observability, cost, and architecture review.",
    sourceType: "MVP",
    strength: "GOOD",
    objectId: "flowdoctor",
    href: "/explore/mvps/flowdoctor",
    github: "https://github.com/Sms1818/FlowDoctor",
    tags: ["mvp", "product", "reliability", "security", "observability"],
  },
  {
    id: "ev-lenny",
    claim: "RAG chat MVP with FastAPI, PostgreSQL, and pgvector",
    summary: "MVP evidence for RAG, persistent chat, and evaluations. Lower priority than PRSense/Neopart.",
    sourceType: "MVP",
    strength: "GOOD",
    objectId: "lenny",
    href: "/explore/mvps/lenny",
    github: "https://github.com/Sms1818/lenny-growth-assistant",
    tags: ["rag", "fastapi", "postgresql", "pgvector", "mvp", "frontend"],
  },
  {
    id: "ev-caspian-94",
    claim: "Merged PR #94 — Bluesky / AT Protocol adapter",
    summary:
      "Open-source evidence: posts, threaded replies, polling, webhook verification, normalization, fakes, tests, and a rebase onto a changed upstream architecture.",
    sourceType: "OPEN_SOURCE",
    strength: "STRONG",
    objectId: "caspian",
    href: "/explore/oss/caspian/pr-94",
    github: "https://github.com/TryCaspian/caspian-sdk/pull/94",
    tags: ["open source", "at protocol", "bluesky", "webhooks", "polling", "integrations"],
  },
  {
    id: "ev-caspian-140",
    claim: "Merged PR #140 — session reliability and per-account locking",
    summary:
      "Open-source concurrency evidence: cached sessions, retry-on-401, and per-account session locking. Not distributed-systems concurrency expertise.",
    sourceType: "OPEN_SOURCE",
    strength: "GOOD",
    objectId: "caspian",
    href: "/explore/oss/caspian/pr-140",
    github: "https://github.com/TryCaspian/caspian-sdk/pull/140",
    tags: ["concurrency", "authentication", "sessions", "reliability", "open source"],
    caveat: "Focused external concurrency evidence — not a claim of distributed-systems expertise.",
  },
  {
    id: "ev-education",
    claim: "B.Tech CSE, Vishwakarma Institute of Technology, Pune, CGPA 8.71",
    summary: "Education evidence. Secondary to professional engineering evidence.",
    sourceType: "EDUCATION",
    strength: "GOOD",
    objectId: "about",
    href: "/explore/about",
    tags: ["education"],
  },
];

export const concepts: Concept[] = [
  {
    id: "event-driven",
    name: "Event-driven systems",
    summary: "Asynchronous pipelines with independent failure boundaries.",
    evidenceIds: ["ev-prsense-overview", "ev-prsense-kafka", "ev-prsense-failures"],
    relatedConceptIds: ["kafka", "reliability", "async"],
  },
  {
    id: "kafka",
    name: "Kafka",
    summary: "Hands-on project evidence through PRSense. Not professional-production Kafka evidence.",
    evidenceIds: ["ev-prsense-kafka"],
    relatedConceptIds: ["event-driven", "async", "reliability"],
  },
  {
    id: "async",
    name: "Asynchronous processing",
    summary: "Webhook ingestion decoupled from clone, diff, inference, and comment posting.",
    evidenceIds: ["ev-prsense-kafka"],
    relatedConceptIds: ["event-driven", "kafka"],
  },
  {
    id: "api-backend",
    name: "API / backend design",
    summary: "Professional APIs at Neopart plus project APIs in PRSense and SupportSync.",
    evidenceIds: ["ev-neopart-apis", "ev-prsense-overview", "ev-supportsync-integrations"],
    relatedConceptIds: ["integrations", "auth"],
  },
  {
    id: "reliability",
    name: "Reliability / failure handling",
    summary: "PRSense failure boundaries and professional automation systems in production.",
    evidenceIds: ["ev-prsense-failures", "ev-neopart-ar", "ev-neopart-reporting"],
    relatedConceptIds: ["event-driven", "kafka"],
  },
  {
    id: "ai-deterministic",
    name: "AI + deterministic systems",
    summary: "AI handles ambiguity; software controls state and actions — especially Neopart AR escalation.",
    evidenceIds: ["ev-neopart-ar", "ev-prsense-ai-boundary"],
    relatedConceptIds: ["applied-ai"],
  },
  {
    id: "applied-ai",
    name: "Applied AI / LLM systems",
    summary: "Professional AR interpretation, PRSense review generation, and RAG projects/MVPs.",
    evidenceIds: ["ev-neopart-ar", "ev-prsense-ai-boundary", "ev-supportsync-rag", "ev-lenny"],
    relatedConceptIds: ["ai-deterministic", "rag"],
  },
  {
    id: "auth",
    name: "Authentication / security",
    summary: "Professional Spring Security / JWT / RBAC plus Caspian session lifecycle.",
    evidenceIds: ["ev-neopart-apis", "ev-caspian-140"],
    relatedConceptIds: ["api-backend", "concurrency"],
  },
  {
    id: "integrations",
    name: "Integrations",
    summary: "Neopart, SupportSync, Caspian, and PRSense all cross system boundaries.",
    evidenceIds: [
      "ev-neopart-integrations",
      "ev-supportsync-integrations",
      "ev-caspian-94",
      "ev-prsense-overview",
    ],
    relatedConceptIds: ["api-backend"],
  },
  {
    id: "cicd",
    name: "Deployment / CI/CD",
    summary: "Professional DigitalOcean / GitHub Actions; Docker/Kubernetes on projects where applicable.",
    evidenceIds: ["ev-neopart-cicd", "ev-prsense-k8s"],
    relatedConceptIds: ["docker"],
  },
  {
    id: "docker",
    name: "Docker",
    summary: "Professional plus project evidence.",
    evidenceIds: ["ev-neopart-cicd", "ev-prsense-k8s", "ev-supportsync-rag"],
    relatedConceptIds: ["cicd"],
  },
  {
    id: "concurrency",
    name: "Concurrency",
    summary: "Per-account session locking in Caspian PR #140. Focused external evidence.",
    evidenceIds: ["ev-caspian-140"],
    relatedConceptIds: ["auth"],
  },
  {
    id: "rag",
    name: "RAG",
    summary: "Project/MVP evidence through SupportSync and Lenny.",
    evidenceIds: ["ev-supportsync-rag", "ev-lenny"],
    relatedConceptIds: ["applied-ai"],
  },
  {
    id: "mvp-execution",
    name: "Product / MVP execution",
    summary: "VeriSpec, FlowDoctor, and Lenny. MVPs, not production platforms.",
    evidenceIds: ["ev-verispec", "ev-flowdoctor", "ev-lenny"],
    relatedConceptIds: ["applied-ai"],
  },
];

export const skills: Skill[] = [
  {
    id: "backend",
    name: "Backend engineering",
    aliases: ["backend", "server-side", "microservices", "spring", "api development"],
    category: "engineering",
    strength: "STRONG",
    summary: "Professional + project evidence.",
    evidenceIds: ["ev-neopart-apis", "ev-neopart-legacy", "ev-prsense-overview"],
  },
  {
    id: "python",
    name: "Python",
    aliases: ["python", "fastapi", "flask"],
    category: "language",
    strength: "STRONG",
    summary: "Professional + projects.",
    evidenceIds: ["ev-neopart-integrations", "ev-neopart-reporting", "ev-supportsync-rag", "ev-lenny"],
  },
  {
    id: "java",
    name: "Java",
    aliases: ["java", "java 21"],
    category: "language",
    strength: "STRONG",
    summary: "Professional + project evidence.",
    evidenceIds: ["ev-neopart-legacy", "ev-neopart-apis", "ev-prsense-overview"],
  },
  {
    id: "spring-boot",
    name: "Spring Boot",
    aliases: ["spring boot", "springboot", "spring mvc", "spring"],
    category: "backend",
    strength: "STRONG",
    summary: "Professional + project evidence.",
    evidenceIds: ["ev-neopart-legacy", "ev-neopart-apis", "ev-prsense-overview"],
  },
  {
    id: "rest",
    name: "REST APIs / integrations",
    aliases: ["rest", "rest apis", "api integrations", "integrations", "webhooks"],
    category: "backend",
    strength: "STRONG",
    summary: "Professional + projects.",
    evidenceIds: [
      "ev-neopart-integrations",
      "ev-neopart-apis",
      "ev-supportsync-integrations",
      "ev-caspian-94",
      "ev-prsense-overview",
    ],
  },
  {
    id: "sql",
    name: "SQL / data",
    aliases: ["sql", "mysql", "postgresql", "postgres", "sql server", "database"],
    category: "data",
    strength: "STRONG",
    summary: "Professional evidence plus project databases.",
    evidenceIds: ["ev-neopart-reporting", "ev-neopart-legacy", "ev-prsense-overview", "ev-lenny"],
  },
  {
    id: "applied-ai",
    name: "Applied AI / LLM systems",
    aliases: ["ai", "llm", "llms", "gemini", "langchain", "prompt engineering", "applied ai"],
    category: "ai",
    strength: "STRONG",
    summary: "Professional + project/MVP evidence. Strong does not mean senior/expert.",
    evidenceIds: ["ev-neopart-ar", "ev-prsense-ai-boundary", "ev-supportsync-rag", "ev-lenny"],
  },
  {
    id: "automation",
    name: "Workflow automation",
    aliases: ["automation", "workflow automation", "internal tools"],
    category: "engineering",
    strength: "STRONG",
    summary: "Professional evidence.",
    evidenceIds: ["ev-neopart-ar", "ev-neopart-reporting", "ev-neopart-integrations"],
  },
  {
    id: "event-driven",
    name: "Event-driven architecture",
    aliases: ["event-driven", "event driven", "async", "asynchronous"],
    category: "architecture",
    strength: "GOOD",
    summary: "Strong project evidence through PRSense.",
    evidenceIds: ["ev-prsense-overview", "ev-prsense-kafka"],
    caveat: "Project evidence through PRSense, not a claim of professional-production event platforms.",
  },
  {
    id: "kafka",
    name: "Kafka",
    aliases: ["kafka", "apache kafka"],
    category: "messaging",
    strength: "GOOD",
    summary: "Hands-on project evidence through PRSense.",
    evidenceIds: ["ev-prsense-kafka"],
    caveat:
      "Kafka evidence is hands-on project evidence rather than documented professional-production experience.",
  },
  {
    id: "rag",
    name: "RAG",
    aliases: ["rag", "retrieval augmented generation", "pinecone", "pgvector", "vector database"],
    category: "ai",
    strength: "GOOD",
    summary: "Project/MVP evidence through SupportSync and Lenny.",
    evidenceIds: ["ev-supportsync-rag", "ev-lenny"],
  },
  {
    id: "auth",
    name: "Authentication / API security",
    aliases: ["jwt", "rbac", "spring security", "oauth", "authentication", "authorization", "api security"],
    category: "security",
    strength: "GOOD",
    summary: "Professional evidence plus Caspian session lifecycle.",
    evidenceIds: ["ev-neopart-apis", "ev-caspian-140"],
  },
  {
    id: "docker",
    name: "Docker",
    aliases: ["docker", "containers", "containerization"],
    category: "devops",
    strength: "GOOD",
    summary: "Professional + project evidence.",
    evidenceIds: ["ev-neopart-cicd", "ev-prsense-k8s", "ev-supportsync-rag"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    aliases: ["kubernetes", "k8s"],
    category: "devops",
    strength: "LIMITED",
    summary: "Project evidence from PRSense.",
    evidenceIds: ["ev-prsense-k8s"],
    caveat: "Kubernetes evidence is project-level.",
  },
  {
    id: "cicd",
    name: "CI/CD",
    aliases: ["ci/cd", "github actions", "pipelines"],
    category: "devops",
    strength: "GOOD",
    summary: "Professional GitHub Actions evidence.",
    evidenceIds: ["ev-neopart-cicd"],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    aliases: ["digitalocean", "digital ocean"],
    category: "cloud",
    strength: "GOOD",
    summary: "Professional deployment evidence.",
    evidenceIds: ["ev-neopart-cicd"],
  },
  {
    id: "concurrency",
    name: "Concurrency",
    aliases: ["concurrency", "locking", "thread safety", "concurrent"],
    category: "engineering",
    strength: "LIMITED",
    summary: "Focused external evidence via Caspian per-account session locking.",
    evidenceIds: ["ev-caspian-140"],
    caveat: "Focused hands-on concurrency evidence — not distributed-systems expertise.",
  },
  {
    id: "frontend",
    name: "Frontend",
    aliases: ["frontend", "react", "next.js", "ui", "full stack", "fullstack"],
    category: "frontend",
    strength: "LIMITED",
    summary: "MVPs demonstrate frontend/end-to-end capability. Not the strongest specialization.",
    evidenceIds: ["ev-verispec", "ev-flowdoctor", "ev-lenny"],
    caveat: "Backend evidence is stronger than frontend evidence.",
  },
  {
    id: "mvp",
    name: "Product / MVP execution",
    aliases: ["mvp", "product", "full-stack"],
    category: "product",
    strength: "GOOD",
    summary: "VeriSpec, FlowDoctor, and Lenny.",
    evidenceIds: ["ev-verispec", "ev-flowdoctor", "ev-lenny"],
  },
  {
    id: "distributed-systems",
    name: "Large-scale distributed systems",
    aliases: ["distributed systems", "high scale", "internet scale"],
    category: "architecture",
    strength: "LIMITED",
    summary: "Architecture/project evidence exists. No proven high-scale production evidence.",
    evidenceIds: ["ev-prsense-overview", "ev-prsense-kafka"],
    caveat: "No proven high-scale production evidence.",
  },
  {
    id: "aws",
    name: "AWS",
    aliases: ["aws", "amazon web services", "ec2", "s3", "lambda", "eks"],
    category: "cloud",
    strength: "NONE",
    summary: "The portfolio does not currently provide evidence of production AWS expertise.",
    evidenceIds: [],
    caveat:
      "The portfolio does not currently provide evidence of production AWS expertise. Related DigitalOcean/CI evidence exists, but that is not AWS.",
  },
  {
    id: "terraform",
    name: "Terraform",
    aliases: ["terraform", "iac", "infrastructure as code"],
    category: "devops",
    strength: "NONE",
    summary: "The current portfolio doesn't provide evidence of Terraform experience.",
    evidenceIds: [],
  },
  {
    id: "seniority",
    name: "Senior / staff-level experience",
    aliases: ["senior", "staff", "principal", "5+ years", "5 years", "7+ years", "10+ years"],
    category: "career",
    strength: "NONE",
    summary: "Approximately 1.5 years of professional experience. Do not present Sahil as senior/staff/principal.",
    evidenceIds: [],
    caveat: "Approximately 1.5 years professional experience — not senior/staff/principal level.",
  },
  {
    id: "gcp",
    name: "GCP",
    aliases: ["gcp", "google cloud"],
    category: "cloud",
    strength: "NONE",
    summary: "The portfolio does not establish deep GCP production expertise.",
    evidenceIds: [],
  },
  {
    id: "opensource",
    name: "Open source",
    aliases: ["open source", "oss", "caspian"],
    category: "engineering",
    strength: "STRONG",
    summary: "Two merged Caspian contributions.",
    evidenceIds: ["ev-caspian-94", "ev-caspian-140"],
  },
];

export const facts = {
  noCollectFlow: true,
  noProfessionalKafka: true,
  noInternetScale: true,
  notSenior: true,
  prsenseNotAutonomousAgent: true,
  absenceOfEvidenceIsNotInability: true,
};
