import SiteHeader from "@/components/SiteHeader";
import StoryProgress from "@/components/StoryProgress";
import TransitionLink from "@/components/TransitionLink";
import { experience, openSource, projects } from "@/lib/portfolio";

export default function StoryPage(){
  const support = projects.find(p=>p.id==="supportsync")!; const verispec=projects.find(p=>p.id==="verispec")!; const flow=projects.find(p=>p.id==="flowdoctor")!;
  return <main className="storyPage">
    <SiteHeader/>
    <StoryProgress/>
    <section className="storyIntro storySection" data-story-section="0"><span className="eyebrow">THE 2-MINUTE TOUR</span><h1>Here’s the quick version of what I’ve been working on.</h1><p>We’ll start with my professional work, then PRSense, a few other builds, and my open-source contributions.</p><div className="scrollCue">Scroll to begin <span>↓</span></div></section>
    <section id="experience" className="storySection splitStory" data-story-section="1"><div className="storyNumber">01</div><div><span className="eyebrow">PROFESSIONAL WORK</span><h2>{experience.company}</h2><p className="storyLead">Backend systems, APIs, integrations, automation and AI-powered workflows used in day-to-day operations.</p><div className="storyFacts">{experience.achievements.slice(0,4).map(x=><div key={x}>{x}</div>)}</div></div><div className="storyVisual softPanel"><span>PRODUCTION SYSTEMS</span><div className="miniFlow"><i>Invoices</i><b>→</b><i>Rules + AI</i><b>→</b><i>Actions</i></div><small>AI helps with ambiguous inputs; the application rules still decide what happens next.</small></div></section>
    <section className="storySection splitStory reverse" data-story-section="2"><div className="storyNumber">02</div><div><span className="eyebrow">ENGINEERING PROJECT</span><h2>PRSense</h2><p className="storyLead">The interesting part was connecting Git, Kafka, Gemini and Bitbucket and handling what happens when one of them fails.</p><div className="inlineFlow"><span>Webhook</span><i>→</i><span>Kafka</span><i>→</i><span>Git diff</span><i>→</i><span>Gemini</span><i>→</i><span>PR comment</span></div><a href="https://github.com/Sms1818/PRSense" target="_blank">GitHub ↗</a></div><div className="storyVisual architectureOrb"><div className="orbit o1"/><div className="orbit o2"/><div className="centerNode">PR</div><span className="n1">Kafka</span><span className="n2">Git</span><span className="n3">AI</span><span className="n4">API</span></div></section>
    <section className="storySection" data-story-section="3"><div className="storyNumber">03</div><span className="eyebrow">SELECTED BUILDS</span><h2>A few other things I’ve built.</h2><div className="storyProjectGrid"><article><small>ENGINEERING PROJECT</small><h3>{support.name}</h3><p>{support.blurb}</p></article><article><small>MVP</small><h3>{verispec.name}</h3><p>{verispec.blurb}</p></article><article><small>MVP</small><h3>{flow.name}</h3><p>{flow.blurb}</p></article></div></section>
    <section className="storySection splitStory" data-story-section="4"><div className="storyNumber">04</div><div><span className="eyebrow">OPEN SOURCE</span><h2>{openSource.name}</h2><p className="storyLead">Work merged into an external codebase after review and iteration.</p><div className="prList">{openSource.prs.map(pr=><a key={pr.id} href={pr.href} target="_blank"><span>#{pr.id}</span><b>{pr.title}</b><i>merged ↗</i></a>)}</div></div><div className="storyVisual softPanel"><span>WHAT I WORKED ON</span><div className="proofWords"><b>Integration</b><b>Auth/session lifecycle</b><b>Concurrency</b><b>Code review</b><b>Upstream iteration</b></div></div></section>
    <section className="storySection storyEnd" data-story-section="5"><span className="eyebrow">THAT’S THE QUICK TOUR</span><h2>Want to go deeper?</h2><p>Open the workspace to browse projects, technical details, open-source work, my resume, Ask Sahil, and role matching.</p><TransitionLink href="/boot?next=/workspace" className="primaryButton">Open the workspace <span>→</span></TransitionLink><small>You can skip the short boot animation if you want.</small></section>
  </main>
}
